name: sender
description: Message Sender with Emoji Reaction Included
version: 0.0.1
homepage: https://github.com/GitFromGeeks/sender

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
